version: "3"

services:
  labrador:
    container_name: labrador
    # image: example/test:${TEST_VERSION}
    build:
      context: ./0dockerfile
    # restart: unless-stoppedcat 
    # env_file: .env
    volumes:
      - ./data:/data
    ports:
      - "5000:80"
